content = input("Digite algo:")
print(f"O tipo primitivo desse valor é {type(content)}")
print(f"Só tem espaços? {content.isspace()}")
print(f"É um número? {content.isnumeric()}")
print(f"É alfabético? {content.isalpha()}")
print(f"É alfanumérico? {content.isalnum()}")
print(f"Está em maiuscula? {content.isupper()}")
print(f"Está em minusculas: {content.islower()}")
print(f"Está capitalizada? {content.istitle()}")
